name: Build Signed Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APKs
        run: ./gradlew assembleRelease --stacktrace

      - name: Find universal APK
        id: apk
        run: |
          FILE=$(ls app/build/outputs/apk/release/mihon-v*.apk | head -n 1)
          echo "apk=$FILE" >> $GITHUB_OUTPUT

      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore temp-release-key.jks \
            -storepass 123456 \
            -keypass 123456 \
            -dname "CN=GitHub,O=CI,C=US" \
            -alias release \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: Sign the APK
        run: |
          jarsigner -verbose \
            -keystore temp-release-key.jks \
            -storepass 123456 \
            -keypass 123456 \
            "${{ steps.apk.outputs.apk }}" \
            release

      - name: Align APK
        run: |
          zipalign -f 4 \
            "${{ steps.apk.outputs.apk }}" \
            app/build/outputs/apk/release/mihon-custom-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Mihon-Custom-Release
          path: app/build/outputs/apk/release/mihon-custom-release.apk
