name: Build Signed Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APKs
        run: ./gradlew assembleRelease --stacktrace

      - name: Generate Keystore (auto)
        run: |
          keytool -genkey -v -keystore temp-release-key.jks \
            -storepass 123456 \
            -keypass 123456 \
            -dname "CN=GitHub,O=CI,C=US" \
            -alias release \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: Find the universal APK
        id: findapk
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*-v*.apk" -not -name "*arm*" -not -name "*x86*" -not -name "*foss*")
          echo "APK_PATH=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Sign the APK
        run: |
          jarsigner -verbose \
            -keystore temp-release-key.jks \
            -storepass 123456 \
            -keypass 123456 \
            "${{ steps.findapk.outputs.APK_PATH }}" \
            release

      - name: Align APK
        run: |
          zipalign -f 4 \
            "${{ steps.findapk.outputs.APK_PATH }}" \
            signed-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Mihon-Signed-Release
          path: signed-release.apk
